# Generated by Django 5.0.3 on 2025-06-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('item_type', models.CharField(choices=[('artist', '작가'), ('artwork', '작품')], max_length=10, verbose_name='항목 유형')),
                ('item_name', models.CharField(max_length=200, verbose_name='항목명')),
                ('item_info', models.CharField(blank=True, max_length=200, verbose_name='항목 정보')),
                ('highlighted_text', models.TextField(verbose_name='하이라이트된 텍스트')),
                ('note', models.TextField(blank=True, verbose_name='메모')),
            ],
            options={
                'verbose_name': '하이라이트',
                'verbose_name_plural': '하이라이트 목록',
                'db_table': 'highlight',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['item_type', '-created_at'], name='highlight_item_ty_d9c9c8_idx'), models.Index(fields=['item_type', 'created_at'], name='highlight_item_ty_71267c_idx'), models.Index(fields=['item_name'], name='highlight_item_na_65880e_idx')],
            },
        ),
    ]
