# Generated by Django 5.0.3 on 2025-06-16 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('highlights', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddIndex(
            model_name='highlight',
            index=models.Index(fields=['item_type', '-created_at'], name='highlight_item_ty_d9c9c8_idx'),
        ),
        migrations.AddIndex(
            model_name='highlight',
            index=models.Index(fields=['item_type', 'created_at'], name='highlight_item_ty_71267c_idx'),
        ),
        migrations.AddIndex(
            model_name='highlight',
            index=models.Index(fields=['item_name'], name='highlight_item_na_65880e_idx'),
        ),
    ]
