# Generated by Django 5.0.3 on 2025-05-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_featured', models.BooleanField(default=False, verbose_name='주요 항목 여부')),
                ('title', models.CharField(max_length=200, verbose_name='작품명')),
                ('image', models.ImageField(blank=True, null=True, upload_to='artworks/images/', verbose_name='작품 이미지')),
                ('artist_name', models.CharField(max_length=100, verbose_name='작가명')),
                ('created_year', models.CharField(blank=True, max_length=10, verbose_name='제작년도')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='좋아요 수')),
            ],
            options={
                'verbose_name': '작품',
                'verbose_name_plural': '작품 목록',
                'ordering': ['artist_name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ArtworkLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '작품 좋아요',
                'verbose_name_plural': '작품 좋아요 목록',
            },
        ),
    ]
