# Generated by Django 5.0.3 on 2025-06-16 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('image', models.ImageField(blank=True, null=True, upload_to='artworks/images/', verbose_name='작품 이미지')),
                ('artist_name', models.CharField(max_length=100, verbose_name='작가명')),
                ('created_year', models.CharField(blank=True, max_length=10, verbose_name='제작년도')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='좋아요 수')),
            ],
            options={
                'verbose_name': '작품',
                'verbose_name_plural': '작품 목록',
                'db_table': 'artwork',
                'ordering': ['artist_name', 'title'],
                'indexes': [models.Index(fields=['artist_name', 'title'], name='artwork_artist__163a24_idx'), models.Index(fields=['artist_name'], name='artwork_artist__a85bf8_idx'), models.Index(fields=['-likes_count'], name='artwork_likes_c_84e9b9_idx'), models.Index(fields=['-created_at'], name='artwork_created_ccd6e7_idx'), models.Index(fields=['created_year'], name='artwork_created_3c5117_idx'), models.Index(fields=['id'], name='artwork_id_75b661_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArtworkLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='artworks.artwork', verbose_name='작품')),
            ],
            options={
                'verbose_name': '작품 좋아요',
                'verbose_name_plural': '작품 좋아요 목록',
                'db_table': 'artwork_like',
            },
        ),
    ]
