# Generated by Django 5.0.3 on 2025-03-23 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exhibitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('is_featured', models.BooleanField(default=False, verbose_name='주요 항목 여부')),
                ('artist', models.CharField(max_length=100, verbose_name='작가')),
                ('year', models.CharField(blank=True, max_length=20, verbose_name='제작연도')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('image', models.ImageField(blank=True, null=True, upload_to='artworks/', verbose_name='이미지')),
                ('type', models.CharField(choices=[('painting', '회화'), ('sculpture', '조각'), ('installation', '설치미술'), ('photography', '사진'), ('media_art', '미디어아트'), ('craft', '공예'), ('drawing', '드로잉'), ('print', '판화'), ('performance', '퍼포먼스'), ('other', '기타')], default='painting', max_length=20, verbose_name='작품 유형')),
                ('medium', models.CharField(blank=True, max_length=200, verbose_name='재료')),
                ('dimensions', models.CharField(blank=True, max_length=100, verbose_name='크기')),
                ('exhibition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artworks', to='exhibitions.exhibition', verbose_name='전시')),
            ],
            options={
                'verbose_name': '작품',
                'verbose_name_plural': '작품 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtworkDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('historical_context', models.TextField(blank=True, verbose_name='역사적 맥락')),
                ('technique_details', models.TextField(blank=True, verbose_name='기법 상세')),
                ('symbolism', models.TextField(blank=True, verbose_name='상징성')),
                ('provenance', models.TextField(blank=True, verbose_name='출처/소장 이력')),
                ('additional_images', models.JSONField(blank=True, default=list, verbose_name='추가 이미지')),
                ('references', models.JSONField(blank=True, default=list, verbose_name='참고 자료')),
                ('artwork', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='artworks.artwork', verbose_name='작품')),
            ],
            options={
                'verbose_name': '작품 상세 정보',
                'verbose_name_plural': '작품 상세 정보 목록',
            },
        ),
    ]
