# Generated by Django 5.0.3 on 2025-05-05 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artworks', '0001_initial'),
        ('exhibitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='exhibition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artworks', to='exhibitions.exhibition', verbose_name='전시'),
        ),
        migrations.AddField(
            model_name='artworklike',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='artworks.artwork', verbose_name='작품'),
        ),
    ]
