# Generated by Django 5.0.3 on 2025-03-23 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_featured', models.BooleanField(default=False, verbose_name='주요 항목 여부')),
                ('venue', models.CharField(max_length=100, verbose_name='장소')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='exhibitions/posters/', verbose_name='포스터 이미지')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='exhibitions/thumbnails/', verbose_name='썸네일 이미지')),
                ('status', models.CharField(choices=[('upcoming', '예정'), ('ongoing', '진행중'), ('ended', '종료')], default='upcoming', max_length=10, verbose_name='상태')),
                ('admission_fee', models.CharField(blank=True, max_length=100, verbose_name='입장료')),
                ('website', models.URLField(blank=True, verbose_name='웹사이트')),
            ],
            options={
                'verbose_name': '전시',
                'verbose_name_plural': '전시 목록',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExhibitionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('curator', models.CharField(blank=True, max_length=100, verbose_name='큐레이터')),
                ('opening_hours', models.CharField(blank=True, max_length=100, verbose_name='관람 시간')),
                ('gallery_map', models.ImageField(blank=True, null=True, upload_to='exhibitions/maps/', verbose_name='전시장 지도')),
                ('additional_images', models.JSONField(blank=True, default=list, verbose_name='추가 이미지')),
                ('related_events', models.JSONField(blank=True, default=list, verbose_name='관련 이벤트')),
                ('exhibition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='exhibitions.exhibition', verbose_name='전시')),
            ],
            options={
                'verbose_name': '전시 상세 정보',
                'verbose_name_plural': '전시 상세 정보 목록',
            },
        ),
    ]
