# Generated by Django 5.0.3 on 2025-06-12 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exhibitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitionlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_exhibitions', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AlterUniqueTogether(
            name='exhibitionlike',
            unique_together={('user', 'exhibition')},
        ),
    ]
