# Generated by Django 5.0.3 on 2025-06-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('name', models.CharField(max_length=100, verbose_name='폴더명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
            ],
            options={
                'verbose_name': '저장 폴더',
                'verbose_name_plural': '저장 폴더 목록',
                'db_table': 'save_folder',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FolderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('item_type', models.CharField(choices=[('artist', '작가'), ('artwork', '작품')], max_length=10, verbose_name='항목 유형')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('life_period', models.CharField(blank=True, max_length=50, verbose_name='생애기간')),
                ('artist_name', models.CharField(blank=True, max_length=100, verbose_name='작가명')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='saved_items/thumbnails/', verbose_name='썸네일')),
            ],
            options={
                'verbose_name': '저장 항목',
                'verbose_name_plural': '저장 항목 목록',
                'db_table': 'saved_item',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocentScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('item_type', models.CharField(choices=[('artist', '작가'), ('artwork', '작품')], max_length=10, verbose_name='항목 유형')),
                ('item_name', models.CharField(max_length=200, verbose_name='항목명')),
                ('item_info', models.CharField(blank=True, max_length=200, verbose_name='항목 정보')),
                ('prompt_text', models.TextField(verbose_name='프롬프트 텍스트')),
                ('prompt_image', models.URLField(blank=True, verbose_name='프롬프트 이미지 URL')),
                ('llm_response', models.TextField(verbose_name='LLM 응답')),
                ('openai_audio', models.FileField(blank=True, null=True, upload_to='docents/openai_audio/', verbose_name='OpenAI 음성')),
                ('polly_audio', models.FileField(blank=True, null=True, upload_to='docents/polly_audio/', verbose_name='Polly 음성')),
                ('timestamps', models.JSONField(blank=True, null=True, verbose_name='타임스탬프')),
            ],
            options={
                'verbose_name': '도슨트 스크립트',
                'verbose_name_plural': '도슨트 스크립트 목록',
                'db_table': 'docent_script',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['item_type', '-created_at'], name='docent_scri_item_ty_75219f_idx'), models.Index(fields=['item_name'], name='docent_scri_item_na_a2a343_idx')],
            },
        ),
    ]
