# Generated by Django 5.0.3 on 2025-05-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_public', models.BooleanField(default=True, verbose_name='공개 여부')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('type', models.CharField(choices=[('personal', '개인 도슨트'), ('official', '공식 도슨트'), ('curator', '큐레이터 도슨트'), ('ai', 'AI 도슨트')], default='personal', max_length=10, verbose_name='도슨트 유형')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='docents/thumbnails/', verbose_name='썸네일 이미지')),
                ('duration', models.PositiveIntegerField(default=30, verbose_name='소요 시간(분)')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='좋아요 수')),
            ],
            options={
                'verbose_name': '도슨트',
                'verbose_name_plural': '도슨트 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocentHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='하이라이트 텍스트')),
                ('start_position', models.PositiveIntegerField(verbose_name='시작 위치')),
                ('end_position', models.PositiveIntegerField(verbose_name='종료 위치')),
                ('note', models.TextField(blank=True, verbose_name='메모')),
                ('is_public', models.BooleanField(default=False, verbose_name='공개 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '도슨트 하이라이트',
                'verbose_name_plural': '도슨트 하이라이트 목록',
                'ordering': ['start_position'],
            },
        ),
        migrations.CreateModel(
            name='DocentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('order', models.PositiveIntegerField(verbose_name='순서')),
                ('commentary', models.TextField(verbose_name='해설')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='docent_audios/', verbose_name='오디오 파일')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='오디오 길이(초)')),
            ],
            options={
                'verbose_name': '도슨트 항목',
                'verbose_name_plural': '도슨트 항목 목록',
                'ordering': ['docent', 'order'],
            },
        ),
        migrations.CreateModel(
            name='DocentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
