# Generated by Django 5.0.3 on 2025-03-23 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artworks', '0001_initial'),
        ('docents', '0001_initial'),
        ('exhibitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='docent',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docents', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='docent',
            name='exhibition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docents', to='exhibitions.exhibition', verbose_name='전시'),
        ),
        migrations.AddField(
            model_name='docentitem',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docent_items', to='artworks.artwork', verbose_name='작품'),
        ),
        migrations.AddField(
            model_name='docentitem',
            name='docent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='docents.docent', verbose_name='도슨트'),
        ),
        migrations.AlterUniqueTogether(
            name='docentitem',
            unique_together={('docent', 'order')},
        ),
    ]
