# Generated by Django 5.0.3 on 2025-06-16 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save_folders', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='folderitem',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='docents.folder', verbose_name='폴더'),
        ),
        migrations.AddField(
            model_name='folderitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['user', 'name'], name='save_folder_user_id_e1e31e_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['user', '-created_at'], name='save_folder_user_id_132649_idx'),
        ),
        migrations.AddIndex(
            model_name='folderitem',
            index=models.Index(fields=['item_type', 'created_at'], name='saved_item_item_ty_ff5ca1_idx'),
        ),
        migrations.AddIndex(
            model_name='folderitem',
            index=models.Index(fields=['user', 'item_type'], name='saved_item_user_id_f8c691_idx'),
        ),
        migrations.AddIndex(
            model_name='folderitem',
            index=models.Index(fields=['user', '-created_at'], name='saved_item_user_id_ebe3cf_idx'),
        ),
        migrations.AddIndex(
            model_name='folderitem',
            index=models.Index(fields=['folder', 'item_type'], name='saved_item_folder__46454f_idx'),
        ),
        migrations.AddIndex(
            model_name='folderitem',
            index=models.Index(fields=['title'], name='saved_item_title_22d28c_idx'),
        ),
        migrations.AddIndex(
            model_name='folderitem',
            index=models.Index(fields=['artist_name'], name='saved_item_artist__618e0c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folderitem',
            unique_together={('folder', 'item_type', 'title')},
        ),
    ]
