# Generated by Django 5.0.3 on 2025-03-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_public', models.BooleanField(default=True, verbose_name='공개 여부')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='art_collections/thumbnails/', verbose_name='썸네일 이미지')),
            ],
            options={
                'verbose_name': '컬렉션',
                'verbose_name_plural': '컬렉션 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('note', models.TextField(blank=True, verbose_name='메모')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
            ],
            options={
                'verbose_name': '컬렉션 항목',
                'verbose_name_plural': '컬렉션 항목 목록',
                'ordering': ['collection', 'order'],
            },
        ),
    ]
