# Generated by Django 5.0.3 on 2025-06-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('visit_date', models.DateField(verbose_name='관람일')),
                ('name', models.CharField(max_length=200, verbose_name='전시명')),
                ('museum', models.CharField(max_length=100, verbose_name='미술관/갤러리')),
                ('note', models.TextField(blank=True, verbose_name='메모')),
                ('image', models.ImageField(blank=True, null=True, upload_to='records/images/', verbose_name='이미지')),
            ],
            options={
                'verbose_name': '전시 관람 기록',
                'verbose_name_plural': '전시 관람 기록 목록',
                'db_table': 'exhibition_record',
            },
        ),
    ]
