# Generated by Django 5.0.3 on 2025-06-12 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitionrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_records', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddIndex(
            model_name='exhibitionrecord',
            index=models.Index(fields=['user', '-visit_date'], name='exhibition__user_id_98892d_idx'),
        ),
        migrations.AddIndex(
            model_name='exhibitionrecord',
            index=models.Index(fields=['-created_at'], name='exhibition__created_01aa88_idx'),
        ),
        migrations.AddIndex(
            model_name='exhibitionrecord',
            index=models.Index(fields=['visit_date'], name='exhibition__visit_d_33e083_idx'),
        ),
        migrations.AddIndex(
            model_name='exhibitionrecord',
            index=models.Index(fields=['museum'], name='exhibition__museum_619f4a_idx'),
        ),
        migrations.AddIndex(
            model_name='exhibitionrecord',
            index=models.Index(fields=['user', '-created_at'], name='exhibition__user_id_b35259_idx'),
        ),
    ]
