# Generated by Django 5.0.3 on 2025-06-16 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('life_period', models.CharField(blank=True, help_text='예: 1853-1890, 1967-현재', max_length=50, verbose_name='출생-사망')),
                ('representative_work', models.CharField(blank=True, max_length=200, verbose_name='대표작')),
                ('image', models.ImageField(blank=True, null=True, upload_to='artists/images/', verbose_name='작가 이미지')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='좋아요 수')),
            ],
            options={
                'verbose_name': '작가',
                'verbose_name_plural': '작가 목록',
                'db_table': 'artist',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='artist_title_224fd1_idx'), models.Index(fields=['-likes_count'], name='artist_likes_c_326fd5_idx'), models.Index(fields=['-created_at'], name='artist_created_a0b946_idx'), models.Index(fields=['id'], name='artist_id_40f4eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArtistLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='artists.artist', verbose_name='작가')),
            ],
            options={
                'verbose_name': '작가 좋아요',
                'verbose_name_plural': '작가 좋아요 목록',
                'db_table': 'artist_like',
            },
        ),
    ]
